Import Data from Kaggle for this demo and prepare for demo data

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None) 

df = pd.read_csv('Balaji Fast Food Sales.csv')
df1=df.copy()
df2=df.copy()
df1.head()
Mapping=df1[['item_name','item_type','item_price']].drop_duplicates(subset='item_name').reset_index(drop=True)
data = df2[['item_name','date','time_of_sale','quantity','transaction_amount']]
data['date'] = data['date'].apply(pd.to_datetime, dayfirst=True)
data.sort_values(by='date')
data.reset_index(drop=True)    
data.head()
data['date']=data['date'].dt.date
data1 = data.melt(
    id_vars = [ 'item_name','date'],
    value_vars= ['quantity','transaction_amount'],
    var_name= 'measure',
    value_name = 'value'
)

Data = data1.pivot_table(
    index=[ 'item_name','measure'],
    columns='date',
    values='value',
    aggfunc='sum',
    fill_value=0
)

Data.reset_index(inplace=True)

<span style="color: green;font-size: 20px; font-weight: bold;">In this demo, weâ€™ll use dataframes below: Data and Mapping. </span> <br> <br>
<span style="color: white; font-size: 15px;">Context: <br> we will receive 'Data' regularly from sales team to generate the latest sales report answering questions below:</span><br><br>
<span style="color: white; font-size: 15px;">1. What's the sales performance of the items and category <br> 2. What drives the change?</span>

#

In [62]:
display(
    Data.head(2),
    Mapping
)

date,item_name,measure,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,2022-01-10,2022-01-11,2022-01-12,2022-02-04,2022-02-05,2022-02-06,2022-02-07,2022-02-08,2022-02-10,2022-02-11,2022-02-12,2022-03-04,2022-03-05,2022-03-07,2022-03-08,2022-03-09,2022-03-10,2022-03-11,2022-03-12,2022-04-04,2022-04-05,2022-04-06,2022-04-07,2022-04-08,2022-04-09,2022-04-10,2022-04-11,2022-04-12,2022-04-14,2022-04-15,2022-04-16,2022-04-17,2022-04-18,2022-04-19,2022-04-20,2022-04-21,2022-04-22,2022-04-23,2022-04-24,2022-04-25,2022-04-26,2022-04-27,2022-04-28,2022-04-29,2022-04-30,2022-05-04,2022-05-05,2022-05-06,2022-05-07,2022-05-08,2022-05-09,2022-05-10,2022-05-11,2022-05-12,2022-05-13,2022-05-14,2022-05-15,2022-05-16,2022-05-17,2022-05-18,2022-05-19,2022-05-20,2022-05-21,2022-05-22,2022-05-23,2022-05-24,2022-05-25,2022-05-26,2022-05-27,2022-05-28,2022-05-29,2022-05-30,2022-05-31,2022-06-05,2022-06-06,2022-06-07,2022-06-08,2022-06-09,2022-06-10,2022-06-11,2022-06-13,2022-06-14,2022-06-15,2022-06-16,2022-06-17,2022-06-18,2022-06-19,2022-06-20,2022-06-22,2022-06-24,2022-06-25,2022-06-26,2022-06-27,2022-06-28,2022-06-29,2022-06-30,2022-07-04,2022-07-05,2022-07-06,2022-07-07,2022-07-08,2022-07-09,2022-07-10,2022-07-11,2022-07-12,2022-07-13,2022-07-14,2022-07-15,2022-07-16,2022-07-17,2022-07-18,2022-07-19,2022-07-20,2022-07-21,2022-07-22,2022-07-23,2022-07-24,2022-07-25,2022-07-26,2022-07-27,2022-07-29,2022-07-30,2022-07-31,2022-08-04,2022-08-05,2022-08-06,2022-08-07,2022-08-08,2022-08-09,2022-08-10,2022-08-11,2022-08-12,2022-08-13,2022-08-14,2022-08-15,2022-08-16,2022-08-17,2022-08-18,2022-08-19,2022-08-20,2022-08-21,2022-08-22,2022-08-23,2022-08-24,2022-08-25,2022-08-26,2022-08-27,2022-08-28,2022-08-30,2022-08-31,2022-09-04,2022-09-05,2022-09-06,2022-09-07,2022-09-08,2022-09-09,2022-09-10,2022-09-11,2022-09-12,2022-09-14,2022-09-15,2022-09-16,2022-09-17,2022-09-18,2022-09-19,2022-09-20,2022-09-21,2022-09-22,2022-09-23,2022-09-24,2022-09-25,2022-09-27,2022-09-28,2022-09-29,2022-09-30,2022-10-04,2022-10-05,2022-10-06,2022-10-07,2022-10-08,2022-10-09,2022-10-10,2022-10-11,2022-10-12,2022-10-13,2022-10-14,2022-10-15,2022-10-16,2022-10-17,2022-10-18,2022-10-19,2022-10-20,2022-10-21,2022-10-22,2022-10-23,2022-10-24,2022-10-26,2022-10-27,2022-10-28,2022-10-29,2022-10-30,2022-10-31,2022-11-04,2022-11-05,2022-11-06,2022-11-07,2022-11-09,2022-11-10,2022-11-11,2022-11-12,2022-11-13,2022-11-14,2022-11-15,2022-11-16,2022-11-17,2022-11-18,2022-11-19,2022-11-20,2022-11-21,2022-11-22,2022-11-23,2022-11-24,2022-11-25,2022-11-26,2022-11-27,2022-11-28,2022-11-29,2022-11-30,2022-12-04,2022-12-05,2022-12-06,2022-12-07,2022-12-08,2022-12-09,2022-12-10,2022-12-11,2022-12-12,2022-12-13,2022-12-14,2022-12-15,2022-12-16,2022-12-17,2022-12-18,2022-12-19,2022-12-20,2022-12-21,2022-12-22,2022-12-23,2022-12-24,2022-12-25,2022-12-26,2022-12-27,2022-12-28,2022-12-29,2022-12-30,2022-12-31,2023-01-01,2023-01-02,2023-01-03,2023-01-13,2023-01-14,2023-01-15,2023-01-16,2023-01-17,2023-01-18,2023-01-19,2023-01-20,2023-01-21,2023-01-22,2023-01-23,2023-01-24,2023-01-25,2023-01-26,2023-01-27,2023-01-28,2023-01-29,2023-01-30,2023-01-31,2023-02-01,2023-02-02,2023-02-03,2023-02-13,2023-02-14,2023-02-15,2023-02-16,2023-02-17,2023-02-18,2023-02-19,2023-02-20,2023-02-21,2023-02-22,2023-02-23,2023-02-24,2023-02-25,2023-02-26,2023-02-27,2023-02-28,2023-03-01,2023-03-02,2023-03-03,2023-03-13,2023-03-14,2023-03-15,2023-03-16,2023-03-17,2023-03-18,2023-03-19,2023-03-20,2023-03-21,2023-03-22,2023-03-23,2023-03-24,2023-03-25,2023-03-26,2023-03-27,2023-03-29,2023-03-30,2023-04-01,2023-04-02,2023-04-03,2023-05-01,2023-05-02,2023-05-03,2023-06-01,2023-06-02,2023-06-03,2023-07-01,2023-07-02,2023-07-03,2023-08-02,2023-08-03,2023-09-02,2023-09-03,2023-10-01,2023-10-02,2023-10-03,2023-11-01,2023-11-02,2023-11-03,2023-12-01,2023-12-02,2023-12-03
0,Aalopuri,quantity,0,13,0,0,0,0,9,12,0,0,0,0,0,0,0,1,0,10,0,13,0,2,0,0,1,0,11,0,0,0,0,0,13,2,0,0,0,0,12,0,5,1,0,0,0,0,0,0,7,8,0,0,0,0,0,0,0,0,0,0,15,7,21,2,0,0,7,3,25,0,3,0,0,0,10,0,11,0,0,25,11,2,3,0,0,0,0,0,4,0,0,0,0,0,0,0,2,15,8,3,0,0,0,11,0,0,0,0,0,0,2,0,0,0,5,12,0,0,0,0,1,0,12,4,13,4,0,9,0,0,0,0,0,0,0,0,0,0,0,10,0,11,13,0,3,0,12,6,0,20,5,0,23,0,0,0,10,8,0,1,0,0,0,0,8,15,9,0,6,15,0,0,9,0,1,14,0,0,0,0,0,15,0,0,0,0,0,12,0,0,0,0,14,0,11,0,0,13,0,1,0,3,0,6,0,0,16,0,0,4,0,0,2,29,0,0,0,0,0,0,0,0,0,2,5,0,15,0,0,0,0,14,0,0,0,15,0,0,0,0,0,0,21,0,14,0,5,0,0,0,5,10,0,14,0,0,0,0,2,4,0,0,15,0,0,0,8,1,0,0,0,0,0,0,0,0,7,0,0,0,15,0,0,4,12,10,25,8,0,0,0,2,0,0,0,0,8,0,3,0,6,0,1,0,3,0,0,0,0,3,0,0,0,0,14,0,0,0,2,0,0,0,0,0,0,0,1,13,0,0,3,0,0,14,0,0,0,0,15,0,0,12,0,0,1,13,0,4
1,Aalopuri,transaction_amount,0,260,0,0,0,0,180,240,0,0,0,0,0,0,0,20,0,200,0,260,0,40,0,0,20,0,220,0,0,0,0,0,260,40,0,0,0,0,240,0,100,20,0,0,0,0,0,0,140,160,0,0,0,0,0,0,0,0,0,0,300,140,420,40,0,0,140,60,500,0,60,0,0,0,200,0,220,0,0,500,220,40,60,0,0,0,0,0,80,0,0,0,0,0,0,0,40,300,160,60,0,0,0,220,0,0,0,0,0,0,40,0,0,0,100,240,0,0,0,0,20,0,240,80,260,80,0,180,0,0,0,0,0,0,0,0,0,0,0,200,0,220,260,0,60,0,240,120,0,400,100,0,460,0,0,0,200,160,0,20,0,0,0,0,160,300,180,0,120,300,0,0,180,0,20,280,0,0,0,0,0,300,0,0,0,0,0,240,0,0,0,0,280,0,220,0,0,260,0,20,0,60,0,120,0,0,320,0,0,80,0,0,40,580,0,0,0,0,0,0,0,0,0,40,100,0,300,0,0,0,0,280,0,0,0,300,0,0,0,0,0,0,420,0,280,0,100,0,0,0,100,200,0,280,0,0,0,0,40,80,0,0,300,0,0,0,160,20,0,0,0,0,0,0,0,0,140,0,0,0,300,0,0,80,240,200,500,160,0,0,0,40,0,0,0,0,160,0,60,0,120,0,20,0,60,0,0,0,0,60,0,0,0,0,280,0,0,0,40,0,0,0,0,0,0,0,20,260,0,0,60,0,0,280,0,0,0,0,300,0,0,240,0,0,20,260,0,80

         item_name  item_type  item_price
0         Aalopuri   Fastfood          20
1          Vadapav   Fastfood          20
2  Sugarcane juice  Beverages          25
3         Panipuri   Fastfood          20
4          Frankie   Fastfood          50
5         Sandwich   Fastfood          60
6      Cold coffee  Beverages          40

In [64]:
DATA2 = Data.melt(
    id_vars = ['item_name','measure'],
    value_vars = Data.columns[2:],
    value_name = 'value',
    var_name = 'date'
)

DATA2.dtypes

item_name    object
measure      object
date         object
value         int64
dtype: object

In [65]:
DATA2['date'] = DATA2['date'].apply(pd.to_datetime, dayfirst=True)
DATA2.dtypes

item_name            object
measure              object
date         datetime64[ns]
value                 int64
dtype: object

In [69]:
Raw_Data = DATA2.merge(Mapping, on='item_name', how='inner')

# display(
#     DATA2.shape,
#     Raw_Data.shape,
#     Raw_Data.head()
# )

Raw_Data = Raw_Data[['item_type','item_name', 'item_price','measure','date','value']]

Raw_Data.head(2)

  item_type item_name  item_price             measure       date  value
0  Fastfood  Aalopuri          20            quantity 2022-01-04      0
1  Fastfood  Aalopuri          20  transaction_amount 2022-01-04      0

In [70]:
path = 'Sales Report Automation - Python.xlsx'

with pd.ExcelWriter(path, engine = 'openpyxl', mode='a', if_sheet_exists= 'replace') as writer:
    Raw_Data.to_excel(writer, sheet_name='Raw_Data', index=False)

print("Data written successfully to 'Raw_Data' sheet! ")

Data written successfully to 'Raw_Data' sheet!