Import Data from Kaggle for this demo and prepare for demo data

In [207]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None) 

df = pd.read_csv('Balaji Fast Food Sales.csv')
df1=df.copy()
df2=df.copy()
df1.head()
Mapping=df1[['item_name','item_type','item_price']].drop_duplicates(subset='item_name').reset_index(drop=True)
data = df2[['item_name','date','time_of_sale','quantity','transaction_amount']]
data['date'] = data['date'].apply(pd.to_datetime, dayfirst=True)
data.sort_values(by='date')
data.reset_index(drop=True)    
data.head()
data1 = data.melt(
    id_vars = [ 'item_name','date'],
    value_vars= ['quantity','transaction_amount'],
    var_name= 'measure',
    value_name = 'value'
)

Data = data1.pivot_table(
    index=[ 'item_name','measure'],
    columns='date',
    values='value',
    aggfunc='sum',
    fill_value=0
)

/var/folders/07/pcxs2zys4msbrvlbxq05c0380000gn/T/ipykernel_44143/2292479117.py:11: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  data['date'] = data['date'].apply(pd.to_datetime, dayfirst=True)
/var/folders/07/pcxs2zys4msbrvlbxq05c0380000gn/T/ipykernel_44143/2292479117.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['date'] = data['date'].apply(pd.to_datetime, dayfirst=True)

<span style="color: green;font-size: 20px; font-weight: bold;">In this demo, weâ€™ll use dataframes below: Data and Mapping. </span> <br> <br>
<span style="color: white; font-size: 15px;">Context: <br> we will receive 'Data' regularly from sales team to generate the latest sales report answering questions below:</span><br><br>
<span style="color: white; font-size: 15px;">1. What's the sales performance of the items and category <br> 2. What drives the change?</span>

#

In [208]:
display(
    Mapping,
    Data.head())

         item_name  item_type  item_price
0         Aalopuri   Fastfood          20
1          Vadapav   Fastfood          20
2  Sugarcane juice  Beverages          25
3         Panipuri   Fastfood          20
4          Frankie   Fastfood          50
5         Sandwich   Fastfood          60
6      Cold coffee  Beverages          40

date                            2022-01-04  2022-01-05  2022-01-06  \
item_name   measure
Aalopuri    quantity                     0          13           0
            transaction_amount           0         260           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-01-07  2022-01-08  2022-01-09  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                    19           0           0
            transaction_amount         760           0           0
Frankie     quantity                     0           5           0

date                            2022-01-10  2022-01-11  2022-01-12  \
item_name   measure
Aalopuri    quantity                     9          12           0
            transaction_amount         180         240           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           8

date                            2022-02-04  2022-02-05  2022-02-06  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                    15          10           4
            transaction_amount         600         400         160
Frankie     quantity                     0           0           0

date                            2022-02-07  2022-02-08  2022-02-10  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                    11          15           2
            transaction_amount         440         600          80
Frankie     quantity                     0           0          12

date                            2022-02-11  2022-02-12  2022-03-04  \
item_name   measure
Aalopuri    quantity                     1           0          10
            transaction_amount          20           0         200
Cold coffee quantity                     0           6           0
            transaction_amount           0         240           0
Frankie     quantity                     4           0           0

date                            2022-03-05  2022-03-07  2022-03-08  \
item_name   measure
Aalopuri    quantity                     0          13           0
            transaction_amount           0         260           0
Cold coffee quantity                     0           2           0
            transaction_amount           0          80           0
Frankie     quantity                     0           0           0

date                            2022-03-09  2022-03-10  2022-03-11  \
item_name   measure
Aalopuri    quantity                     2           0           0
            transaction_amount          40           0           0
Cold coffee quantity                     0           0          10
            transaction_amount           0           0         400
Frankie     quantity                     0          13           6

date                            2022-03-12  2022-04-04  2022-04-05  \
item_name   measure
Aalopuri    quantity                     1           0          11
            transaction_amount          20           0         220
Cold coffee quantity                     0          19           0
            transaction_amount           0         760           0
Frankie     quantity                     0           0           7

date                            2022-04-06  2022-04-07  2022-04-08  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-04-09  2022-04-10  2022-04-11  \
item_name   measure
Aalopuri    quantity                     0           0          13
            transaction_amount           0           0         260
Cold coffee quantity                     0          10           0
            transaction_amount           0         400           0
Frankie     quantity                     0           0           0

date                            2022-04-12  2022-04-14  2022-04-15  \
item_name   measure
Aalopuri    quantity                     2           0           0
            transaction_amount          40           0           0
Cold coffee quantity                    15           0           0
            transaction_amount         600           0           0
Frankie     quantity                    19           0           0

date                            2022-04-16  2022-04-17  2022-04-18  \
item_name   measure
Aalopuri    quantity                     0           0          12
            transaction_amount           0           0         240
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     6           5           0

date                            2022-04-19  2022-04-20  2022-04-21  \
item_name   measure
Aalopuri    quantity                     0           5           1
            transaction_amount           0         100          20
Cold coffee quantity                     1          16           0
            transaction_amount          40         640           0
Frankie     quantity                     0           0           0

date                            2022-04-22  2022-04-23  2022-04-24  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-04-25  2022-04-26  2022-04-27  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0          14           0
            transaction_amount           0         560           0
Frankie     quantity                     0           0           0

date                            2022-04-28  2022-04-29  2022-04-30  \
item_name   measure
Aalopuri    quantity                     7           8           0
            transaction_amount         140         160           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0          13

date                            2022-05-04  2022-05-05  2022-05-06  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0          23           0
            transaction_amount           0         920           0
Frankie     quantity                     2           0           0

date                            2022-05-07  2022-05-08  2022-05-09  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-05-10  2022-05-11  2022-05-12  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           6
            transaction_amount           0           0         240
Frankie     quantity                     0           9           0

date                            2022-05-13  2022-05-14  2022-05-15  \
item_name   measure
Aalopuri    quantity                    15           7          21
            transaction_amount         300         140         420
Cold coffee quantity                    14          10           2
            transaction_amount         560         400          80
Frankie     quantity                     0           5           0

date                            2022-05-16  2022-05-17  2022-05-18  \
item_name   measure
Aalopuri    quantity                     2           0           0
            transaction_amount          40           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                    15           0          13

date                            2022-05-19  2022-05-20  2022-05-21  \
item_name   measure
Aalopuri    quantity                     7           3          25
            transaction_amount         140          60         500
Cold coffee quantity                     3           0          13
            transaction_amount         120           0         520
Frankie     quantity                     0           0           0

date                            2022-05-22  2022-05-23  2022-05-24  \
item_name   measure
Aalopuri    quantity                     0           3           0
            transaction_amount           0          60           0
Cold coffee quantity                     0           0           3
            transaction_amount           0           0         120
Frankie     quantity                    12           0          13

date                            2022-05-25  2022-05-26  2022-05-27  \
item_name   measure
Aalopuri    quantity                     0           0          10
            transaction_amount           0           0         200
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                    11           0           7

date                            2022-05-28  2022-05-29  2022-05-30  \
item_name   measure
Aalopuri    quantity                     0          11           0
            transaction_amount           0         220           0
Cold coffee quantity                     0           0           3
            transaction_amount           0           0         120
Frankie     quantity                     0           0          10

date                            2022-05-31  2022-06-05  2022-06-06  \
item_name   measure
Aalopuri    quantity                     0          25          11
            transaction_amount           0         500         220
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     8           0           9

date                            2022-06-07  2022-06-08  2022-06-09  \
item_name   measure
Aalopuri    quantity                     2           3           0
            transaction_amount          40          60           0
Cold coffee quantity                     0           0           7
            transaction_amount           0           0         280
Frankie     quantity                     0           0           0

date                            2022-06-10  2022-06-11  2022-06-13  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     2          34           0
            transaction_amount          80        1360           0
Frankie     quantity                     0           4           6

date                            2022-06-14  2022-06-15  2022-06-16  \
item_name   measure
Aalopuri    quantity                     0           4           0
            transaction_amount           0          80           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     1           0          12

date                            2022-06-17  2022-06-18  2022-06-19  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           6

date                            2022-06-20  2022-06-22  2022-06-24  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     5           0           0
            transaction_amount         200           0           0
Frankie     quantity                     0           0           7

date                            2022-06-25  2022-06-26  2022-06-27  \
item_name   measure
Aalopuri    quantity                     2          15           8
            transaction_amount          40         300         160
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                    10           0          10

date                            2022-06-28  2022-06-29  2022-06-30  \
item_name   measure
Aalopuri    quantity                     3           0           0
            transaction_amount          60           0           0
Cold coffee quantity                     0          14           0
            transaction_amount           0         560           0
Frankie     quantity                    13           0          20

date                            2022-07-04  2022-07-05  2022-07-06  \
item_name   measure
Aalopuri    quantity                     0          11           0
            transaction_amount           0         220           0
Cold coffee quantity                     0           8           0
            transaction_amount           0         320           0
Frankie     quantity                     0           0           8

date                            2022-07-07  2022-07-08  2022-07-09  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                    10           0           0
            transaction_amount         400           0           0
Frankie     quantity                     0           0           2

date                            2022-07-10  2022-07-11  2022-07-12  \
item_name   measure
Aalopuri    quantity                     0           0           2
            transaction_amount           0           0          40
Cold coffee quantity                     7          10           0
            transaction_amount         280         400           0
Frankie     quantity                     7           0           0

date                            2022-07-13  2022-07-14  2022-07-15  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-07-16  2022-07-17  2022-07-18  \
item_name   measure
Aalopuri    quantity                     5          12           0
            transaction_amount         100         240           0
Cold coffee quantity                    10           0           0
            transaction_amount         400           0           0
Frankie     quantity                     0           6           0

date                            2022-07-19  2022-07-20  2022-07-21  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     3           6           0

date                            2022-07-22  2022-07-23  2022-07-24  \
item_name   measure
Aalopuri    quantity                     1           0          12
            transaction_amount          20           0         240
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0          10

date                            2022-07-25  2022-07-26  2022-07-27  \
item_name   measure
Aalopuri    quantity                     4          13           4
            transaction_amount          80         260          80
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     0           0           0

date                            2022-07-29  2022-07-30  2022-07-31  \
item_name   measure
Aalopuri    quantity                     0           9           0
            transaction_amount           0         180           0
Cold coffee quantity                     0           0           9
            transaction_amount           0           0         360
Frankie     quantity                     5           0           7

date                            2022-08-04  2022-08-05  2022-08-06  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0           0
            transaction_amount           0           0           0
Frankie     quantity                     1          13           0

date                            2022-08-07  2022-08-08  2022-08-09  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0          12           0
            transaction_amount           0         480           0
Frankie     quantity                     5           0          19

date                            2022-08-10  2022-08-11  2022-08-12  \
item_name   measure
Aalopuri    quantity                     0           0           0
            transaction_amount           0           0           0
Cold coffee quantity                     0           0          13
            transaction_amount           0           0         520
Frankie     quantity                     7           0           0

date                            2022-08-13  2022-08-14  2022-08-15  \
item_name   measure
Aalopuri    quantity                     0          10           0
            transaction_amount           0         200           0
Cold coffee quantity                     0           7          10
            transaction_amount           0         280         400

In [217]:
import pandas as pd
DATA = Data.copy().reset_index()
DATA.head(1)

date,item_name,measure,2022-01-04 00:00:00,2022-01-05 00:00:00,2022-01-06 00:00:00,2022-01-07 00:00:00,2022-01-08 00:00:00,2022-01-09 00:00:00,2022-01-10 00:00:00,2022-01-11 00:00:00,2022-01-12 00:00:00,2022-02-04 00:00:00,2022-02-05 00:00:00,2022-02-06 00:00:00,2022-02-07 00:00:00,2022-02-08 00:00:00,2022-02-10 00:00:00,2022-02-11 00:00:00,2022-02-12 00:00:00,2022-03-04 00:00:00,2022-03-05 00:00:00,2022-03-07 00:00:00,2022-03-08 00:00:00,2022-03-09 00:00:00,2022-03-10 00:00:00,2022-03-11 00:00:00,2022-03-12 00:00:00,2022-04-04 00:00:00,2022-04-05 00:00:00,2022-04-06 00:00:00,2022-04-07 00:00:00,2022-04-08 00:00:00,2022-04-09 00:00:00,2022-04-10 00:00:00,2022-04-11 00:00:00,2022-04-12 00:00:00,2022-04-14 00:00:00,2022-04-15 00:00:00,2022-04-16 00:00:00,2022-04-17 00:00:00,2022-04-18 00:00:00,2022-04-19 00:00:00,2022-04-20 00:00:00,2022-04-21 00:00:00,2022-04-22 00:00:00,2022-04-23 00:00:00,2022-04-24 00:00:00,2022-04-25 00:00:00,2022-04-26 00:00:00,2022-04-27 00:00:00,2022-04-28 00:00:00,2022-04-29 00:00:00,2022-04-30 00:00:00,2022-05-04 00:00:00,2022-05-05 00:00:00,2022-05-06 00:00:00,2022-05-07 00:00:00,2022-05-08 00:00:00,2022-05-09 00:00:00,2022-05-10 00:00:00,2022-05-11 00:00:00,2022-05-12 00:00:00,2022-05-13 00:00:00,2022-05-14 00:00:00,2022-05-15 00:00:00,2022-05-16 00:00:00,2022-05-17 00:00:00,2022-05-18 00:00:00,2022-05-19 00:00:00,2022-05-20 00:00:00,2022-05-21 00:00:00,2022-05-22 00:00:00,2022-05-23 00:00:00,2022-05-24 00:00:00,2022-05-25 00:00:00,2022-05-26 00:00:00,2022-05-27 00:00:00,2022-05-28 00:00:00,2022-05-29 00:00:00,2022-05-30 00:00:00,2022-05-31 00:00:00,2022-06-05 00:00:00,2022-06-06 00:00:00,2022-06-07 00:00:00,2022-06-08 00:00:00,2022-06-09 00:00:00,2022-06-10 00:00:00,2022-06-11 00:00:00,2022-06-13 00:00:00,2022-06-14 00:00:00,2022-06-15 00:00:00,2022-06-16 00:00:00,2022-06-17 00:00:00,2022-06-18 00:00:00,2022-06-19 00:00:00,2022-06-20 00:00:00,2022-06-22 00:00:00,2022-06-24 00:00:00,2022-06-25 00:00:00,2022-06-26 00:00:00,2022-06-27 00:00:00,2022-06-28 00:00:00,2022-06-29 00:00:00,2022-06-30 00:00:00,2022-07-04 00:00:00,2022-07-05 00:00:00,2022-07-06 00:00:00,2022-07-07 00:00:00,2022-07-08 00:00:00,2022-07-09 00:00:00,2022-07-10 00:00:00,2022-07-11 00:00:00,2022-07-12 00:00:00,2022-07-13 00:00:00,2022-07-14 00:00:00,2022-07-15 00:00:00,2022-07-16 00:00:00,2022-07-17 00:00:00,2022-07-18 00:00:00,2022-07-19 00:00:00,2022-07-20 00:00:00,2022-07-21 00:00:00,2022-07-22 00:00:00,2022-07-23 00:00:00,2022-07-24 00:00:00,2022-07-25 00:00:00,2022-07-26 00:00:00,2022-07-27 00:00:00,2022-07-29 00:00:00,2022-07-30 00:00:00,2022-07-31 00:00:00,2022-08-04 00:00:00,2022-08-05 00:00:00,2022-08-06 00:00:00,2022-08-07 00:00:00,2022-08-08 00:00:00,2022-08-09 00:00:00,2022-08-10 00:00:00,2022-08-11 00:00:00,2022-08-12 00:00:00,2022-08-13 00:00:00,2022-08-14 00:00:00,2022-08-15 00:00:00,2022-08-16 00:00:00,2022-08-17 00:00:00,2022-08-18 00:00:00,2022-08-19 00:00:00,2022-08-20 00:00:00,2022-08-21 00:00:00,2022-08-22 00:00:00,2022-08-23 00:00:00,2022-08-24 00:00:00,2022-08-25 00:00:00,2022-08-26 00:00:00,2022-08-27 00:00:00,2022-08-28 00:00:00,2022-08-30 00:00:00,2022-08-31 00:00:00,2022-09-04 00:00:00,2022-09-05 00:00:00,2022-09-06 00:00:00,2022-09-07 00:00:00,2022-09-08 00:00:00,2022-09-09 00:00:00,2022-09-10 00:00:00,2022-09-11 00:00:00,2022-09-12 00:00:00,2022-09-14 00:00:00,2022-09-15 00:00:00,2022-09-16 00:00:00,2022-09-17 00:00:00,2022-09-18 00:00:00,2022-09-19 00:00:00,2022-09-20 00:00:00,2022-09-21 00:00:00,2022-09-22 00:00:00,2022-09-23 00:00:00,2022-09-24 00:00:00,2022-09-25 00:00:00,2022-09-27 00:00:00,2022-09-28 00:00:00,2022-09-29 00:00:00,2022-09-30 00:00:00,2022-10-04 00:00:00,2022-10-05 00:00:00,2022-10-06 00:00:00,2022-10-07 00:00:00,2022-10-08 00:00:00,2022-10-09 00:00:00,2022-10-10 00:00:00,2022-10-11 00:00:00,2022-10-12 00:00:00,2022-10-13 00:00:00,2022-10-14 00:00:00,2022-10-15 00:00:00,2022-10-16 00:00:00,2022-10-17 00:00:00,2022-10-18 00:00:00,2022-10-19 00:00:00,2022-10-20 00:00:00,2022-10-21 00:00:00,2022-10-22 00:00:00,2022-10-23 00:00:00,2022-10-24 00:00:00,2022-10-26 00:00:00,2022-10-27 00:00:00,2022-10-28 00:00:00,2022-10-29 00:00:00,2022-10-30 00:00:00,2022-10-31 00:00:00,2022-11-04 00:00:00,2022-11-05 00:00:00,2022-11-06 00:00:00,2022-11-07 00:00:00,2022-11-09 00:00:00,2022-11-10 00:00:00,2022-11-11 00:00:00,2022-11-12 00:00:00,2022-11-13 00:00:00,2022-11-14 00:00:00,2022-11-15 00:00:00,2022-11-16 00:00:00,2022-11-17 00:00:00,2022-11-18 00:00:00,2022-11-19 00:00:00,2022-11-20 00:00:00,2022-11-21 00:00:00,2022-11-22 00:00:00,2022-11-23 00:00:00,2022-11-24 00:00:00,2022-11-25 00:00:00,2022-11-26 00:00:00,2022-11-27 00:00:00,2022-11-28 00:00:00,2022-11-29 00:00:00,2022-11-30 00:00:00,2022-12-04 00:00:00,2022-12-05 00:00:00,2022-12-06 00:00:00,2022-12-07 00:00:00,2022-12-08 00:00:00,2022-12-09 00:00:00,2022-12-10 00:00:00,2022-12-11 00:00:00,2022-12-12 00:00:00,2022-12-13 00:00:00,2022-12-14 00:00:00,2022-12-15 00:00:00,2022-12-16 00:00:00,2022-12-17 00:00:00,2022-12-18 00:00:00,2022-12-19 00:00:00,2022-12-20 00:00:00,2022-12-21 00:00:00,2022-12-22 00:00:00,2022-12-23 00:00:00,2022-12-24 00:00:00,2022-12-25 00:00:00,2022-12-26 00:00:00,2022-12-27 00:00:00,2022-12-28 00:00:00,2022-12-29 00:00:00,2022-12-30 00:00:00,2022-12-31 00:00:00,2023-01-01 00:00:00,2023-01-02 00:00:00,2023-01-03 00:00:00,2023-01-13 00:00:00,2023-01-14 00:00:00,2023-01-15 00:00:00,2023-01-16 00:00:00,2023-01-17 00:00:00,2023-01-18 00:00:00,2023-01-19 00:00:00,2023-01-20 00:00:00,2023-01-21 00:00:00,2023-01-22 00:00:00,2023-01-23 00:00:00,2023-01-24 00:00:00,2023-01-25 00:00:00,2023-01-26 00:00:00,2023-01-27 00:00:00,2023-01-28 00:00:00,2023-01-29 00:00:00,2023-01-30 00:00:00,2023-01-31 00:00:00,2023-02-01 00:00:00,2023-02-02 00:00:00,2023-02-03 00:00:00,2023-02-13 00:00:00,2023-02-14 00:00:00,2023-02-15 00:00:00,2023-02-16 00:00:00,2023-02-17 00:00:00,2023-02-18 00:00:00,2023-02-19 00:00:00,2023-02-20 00:00:00,2023-02-21 00:00:00,2023-02-22 00:00:00,2023-02-23 00:00:00,2023-02-24 00:00:00,2023-02-25 00:00:00,2023-02-26 00:00:00,2023-02-27 00:00:00,2023-02-28 00:00:00,2023-03-01 00:00:00,2023-03-02 00:00:00,2023-03-03 00:00:00,2023-03-13 00:00:00,2023-03-14 00:00:00,2023-03-15 00:00:00,2023-03-16 00:00:00,2023-03-17 00:00:00,2023-03-18 00:00:00,2023-03-19 00:00:00,2023-03-20 00:00:00,2023-03-21 00:00:00,2023-03-22 00:00:00,2023-03-23 00:00:00,2023-03-24 00:00:00,2023-03-25 00:00:00,2023-03-26 00:00:00,2023-03-27 00:00:00,2023-03-29 00:00:00,2023-03-30 00:00:00,2023-04-01 00:00:00,2023-04-02 00:00:00,2023-04-03 00:00:00,2023-05-01 00:00:00,2023-05-02 00:00:00,2023-05-03 00:00:00,2023-06-01 00:00:00,2023-06-02 00:00:00,2023-06-03 00:00:00,2023-07-01 00:00:00,2023-07-02 00:00:00,2023-07-03 00:00:00,2023-08-02 00:00:00,2023-08-03 00:00:00,2023-09-02 00:00:00,2023-09-03 00:00:00,2023-10-01 00:00:00,2023-10-02 00:00:00,2023-10-03 00:00:00,2023-11-01 00:00:00,2023-11-02 00:00:00,2023-11-03 00:00:00,2023-12-01 00:00:00,2023-12-02 00:00:00,2023-12-03 00:00:00
0,Aalopuri,quantity,0,13,0,0,0,0,9,12,0,0,0,0,0,0,0,1,0,10,0,13,0,2,0,0,1,0,11,0,0,0,0,0,13,2,0,0,0,0,12,0,5,1,0,0,0,0,0,0,7,8,0,0,0,0,0,0,0,0,0,0,15,7,21,2,0,0,7,3,25,0,3,0,0,0,10,0,11,0,0,25,11,2,3,0,0,0,0,0,4,0,0,0,0,0,0,0,2,15,8,3,0,0,0,11,0,0,0,0,0,0,2,0,0,0,5,12,0,0,0,0,1,0,12,4,13,4,0,9,0,0,0,0,0,0,0,0,0,0,0,10,0,11,13,0,3,0,12,6,0,20,5,0,23,0,0,0,10,8,0,1,0,0,0,0,8,15,9,0,6,15,0,0,9,0,1,14,0,0,0,0,0,15,0,0,0,0,0,12,0,0,0,0,14,0,11,0,0,13,0,1,0,3,0,6,0,0,16,0,0,4,0,0,2,29,0,0,0,0,0,0,0,0,0,2,5,0,15,0,0,0,0,14,0,0,0,15,0,0,0,0,0,0,21,0,14,0,5,0,0,0,5,10,0,14,0,0,0,0,2,4,0,0,15,0,0,0,8,1,0,0,0,0,0,0,0,0,7,0,0,0,15,0,0,4,12,10,25,8,0,0,0,2,0,0,0,0,8,0,3,0,6,0,1,0,3,0,0,0,0,3,0,0,0,0,14,0,0,0,2,0,0,0,0,0,0,0,1,13,0,0,3,0,0,14,0,0,0,0,15,0,0,12,0,0,1,13,0,4

In [262]:
DATA2 = DATA.melt(
    id_vars=['item_name','measure'],
    value_vars = DATA.columns[2:],
    var_name = 'date',
    value_name = 'value'
)

DATA2['date'] = DATA2['date'].apply(pd.to_datetime,dayfirst=True).dt.normalize()

DATA2.head()

     item_name             measure       date  value
0     Aalopuri            quantity 2022-01-04      0
1     Aalopuri  transaction_amount 2022-01-04      0
2  Cold coffee            quantity 2022-01-04      0
3  Cold coffee  transaction_amount 2022-01-04      0
4      Frankie            quantity 2022-01-04      0

In [263]:
DATA3 = DATA2.merge(Mapping, on='item_name', how ='left')
Raw_data = DATA3[['item_type',
                  'item_name',
                  'item_price',
                  'measure',
                  'date',
                  'value'
                  ]].sort_values(['item_type', 'item_name', 'date'])
Raw_data.head()

    item_type    item_name  item_price             measure       date  value
2   Beverages  Cold coffee          40            quantity 2022-01-04      0
3   Beverages  Cold coffee          40  transaction_amount 2022-01-04      0
16  Beverages  Cold coffee          40            quantity 2022-01-05      0
17  Beverages  Cold coffee          40  transaction_amount 2022-01-05      0
30  Beverages  Cold coffee          40            quantity 2022-01-06      0

In [265]:
with pd.ExcelWriter('Test.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    Raw_data.to_excel(writer, sheet_name='Raw_Data', index=False)

print("Data written to the 'Raw_Data' sheet successfully.")

Data written to the 'Raw_Data' sheet successfully.